backend:
  name: github
  repo: Rashmi-278/Valley-of-the-commons-2026-WIKI
  branch: master

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: valley
    label: "Valley of the Commons"
    folder: docs/valley
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }

  - name: operations
    label: "Operations"
    folder: docs/operations
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }

  - name: accommodation
    label: "Accommodation"
    folder: docs/accommodation
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }

  - name: logistics
    label: "Logistics"
    folder: docs/logistics
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }

  - name: team
    label: "Team"
    folder: docs/team
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }

  - name: programming
    label: "Programming"
    folder: docs/programming
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }

  - name: speakers
    label: "Speakers & Collaborators"
    folder: docs/speakers
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: description, label: Description, widget: string, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: participants
    label: "Participants"
    folder: docs/participants
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }

  - name: guides
    label: "Guides"
    folder: docs/guides
    create: true
    extension: md
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Sidebar Position, widget: number }
      - { name: body, label: Body, widget: markdown }
